### ISSUE TITLE
Reduce with empty array when no service is hidden

### ISSUE THREAD

**Issue by Mte90** [Mte90/Share-Backported#115]
At line https://github.com/Mte90/Share-Backported/blob/master/modal/modal.js#L163 I get `TypeError: reduce of empty array with no initial value` with a link to https://developer.mozilla.org/it/docs/Web/JavaScript/Reference/Errors/Reduce_of_empty_array_with_no_initial_value

**Comment by Ryuno-Ki** [comment]
Confirmed. Working on a fix. Regression of #86. You can assign the ticket to me.

(Could be that the network I am currently connected to does not allow pushes to GitHub, so wait ~2 hours until I'm at home and can push it).

**Comment by Ryuno-Ki** [comment]
Okay, I have a fix.
The bug lies within https://github.com/Mte90/Share-Backported/blob/683e3e5da242189df184177c28de0f32e535534a/modal/modal.js#L149-L167 (you can get a permalink by hitting <kbd>y</kbd> on a page. This yields this nice view).

Namely, the filter can turn the array into an empty one. The `.sort()` is fine with that, but the `.reduce()` isn't. Can't upload my changes right now, but will do so later today.

**Comment by Ryuno-Ki** [comment]
@Mte90 I'm afraid, you'd need to publish another patch version after #116.
