### ISSUE TITLE
Containers lost after disabling and re-enabling

### ISSUE THREAD

**Issue by scienceisnotdead** [Mte90/Share-Backported#175]
Hello,

Firefox 97.0.1 (64-bit), Windows 10. I had 15 different containers with their particular color and icon. After disabling and re-enabling the Share-Backported extension, it's the default: personal, work, etc. Hopefully they remain somewhere in a config file; maybe?

Thanks

**Comment by Mte90** [comment]
I don't understand with the extension you are losing the containers settings?

Our code just check the window opened is of a container to still open inside it:

* https://github.com/Mte90/Share-Backported/blob/849b5d49076ca404212b1bff009cead07f1234a7/background.js#L10
* https://github.com/Mte90/Share-Backported/blob/584264c0d478c8f27c33c3f524a334f12f1ea0e3/modal/modal.js#L42

It is the first report that I get about it and the code is the same since 2-3 years.
It is happening with other extensions?

I don't use containers so I am not able to test it.

**Comment by Mte90** [comment]
Closing after no answers.
