### ISSUE TITLE
Add Support for posting to Wordpress

### ISSUE THREAD

**Issue by tgott** [Mte90/Share-Backported#177]
I chose this extension years ago and have always favored it above the alternative which is AddToAny. The offering of alternative Social Media such as Mastadon, MeWe, and Parler are just a few of the reasons I appreciate Share-Backported. I also like the interface. Can you please put the cream on the crop **by adding Wordpress** to the repertoire :-)

**Comment by Mte90** [comment]
WordPress doesn't have any share system as it is a blog and not a social network, so I can't add it (I am a WordPress Core contributor so I know about it).
Anyway thanks :-)

**Comment by tgott** [comment]
No need to respond to this since I don't have much more than a user-level knowledge of WordPress, and so I am content to trust you.  I am going to guess there must be some fundamental difference between the way Shared-Backported and [AddToAny](https://addons.mozilla.org/en-US/firefox/addon/addtoany-share/) works since I just used AddToAny to post to my blog over at wordpress.com

I hope you aren't insulted by my making this observation. I've looked around at the work that you do and I have nothing but appreciation. Thank you for everything that you are doing. All the best !

**Comment by Mte90** [comment]
No problem, it is not clear often how works those services.

The extension is based on avoiding any integrations with services like instead addtoany has. The extension is so simple because is just sharing some data (url etc) to a link of the specific service without any specific configuration.

So there are some services that doesn't offer those things or require specific code only for them to do it and I want that the extension is simple otherwise all those services will be difficult to manage during the time.
