### ISSUE TITLE
A few requests

### ISSUE THREAD

**Issue by ReBOPmd** [Mte90/Share-Backported#189]
This app is really nice. I like the aesthetics more than Addtoany, and the fact that it opens a popup to share. However Addtoany seems more helpful because you can add most any site, and customize the logo of each one you add.

Requests:

For apps that don't have an easy sharing url scheme, it would be great to at least copy the current URL and then open the site for that app, so you can just paste and share.

Apps I'd like to see this for:

-  Facebook Messenger, Google Messages, Lemmy, Threads, Bluesky, signal, and of course email.
- Also just a copy url function in the window might not be half-bad

And finally please add the ability to add your own sites, make it clear and add the ability to add icons or change icons for each site.

**Comment by Mte90** [comment]
I am sad that I have to close the ticket:

* https://github.com/Mte90/Share-Backported/issues/186
* https://github.com/Mte90/Share-Backported/issues/179
* https://github.com/Mte90/Share-Backported/issues/178

Those services don't have any share url or I wasn't able to find them. I don't know for BLuesky and signal.
For email this depends on the service, infact we have Gmail and Outlook because they offer a URL that autofill the page.

About the copy the text selected and autofill the window, instead to use the page title it is already implemented.

This extension compared to Addtoany doesn't use API or SDK, but just URL provided by the various services so it is more privacy friendly and fast so not all the services offer that.

**Comment by go2tom42** [comment]
Bluesky share URL
`https://bsky.app/intent/compose?text=Hello+https://google.com`

**Comment by Mte90** [comment]
@go2tom42 this is a closed ticket, can you open a new one just for bluesky?
