### ISSUE TITLE
Add a feature to customize the format of text to share

### ISSUE THREAD

**Issue by tubo28** [Mte90/Share-Backported#36]
Current format of text to share on twitter is like following:

```
{{title}} {{url}}
```

For this page, it will be like following:

```
New Issue · Mte90/Share-Backported https://github.com/Mte90/Share-Backported/issues/new
```

But I always add a comment, quote the title and add a slash manually like following:

```
I want. / "Now browsing: New Issue · Mte90/Share-Backported" https://github.com/Mte90/Share-Backported/issues/new
```

But it would be great if all except the comment was prepared automatically. How about adding a feature to customize the format to share text?

**Comment by Mte90** [comment]
Cool idea, I am not sure when I can implement it but is a cool idea!

**Comment by Ryuno-Ki** [comment]
Hi @tubo28,

you said „always” … so do you have the same pattern across all pages?
I am thinking, whether we should prepopulate the UI (a `<textarea>`?) or allow the setup of some patterns first … or both. :thinking:

**Comment by Mte90** [comment]
We can add a `textarea` in settings for a placeholder text like a prefix or suffix area.
What do you think?

**Comment by Ryuno-Ki** [comment]
Meh, okay my idea won't work: Turning the string into kinda template literal. Found a trick on StackOverflow (where else?) which would morph it into a `Function()`, but CSP is blocking this.

So I looked at npm for alternatives and found
- [pupa](https://www.npmjs.com/package/pupa)
- [string-interpolation](https://www.npmjs.com/package/string-interpolation)
- [micromustache](https://www.npmjs.com/package/micromustache)

Since they are all node-based, they won't work for us. But we could look at their API for inspiration.
I'm afraid, throwing a RegExp is the easiest solution for now. But it could come back and bite us down the road. Micromustache is applying a full tokenisation-parse-interpret cycle, which feels overkill …

What do you think, @Mte90 ? (I hope, I didn't lost you…)

**Comment by Ryuno-Ki** [comment]
That's what we will end up with.
But RegExp can come back and bite you :-/

Will provide a PR today or tomorrow.
Can someone else style it afterwards?

**Comment by Ryuno-Ki** [comment]
Okay, I need some feedback for https://github.com/Mte90/Share-Backported/compare/master...Ryuno-Ki:36-customise-share-format?expand=1

I created the `<textarea>` in `modal.html` and read its value in `modal.js` (resp. restore it on next load).
I then looked into how I can get the current share text. Therefore I looked at `background.js` and learned, that it is piped in: https://github.com/Mte90/Share-Backported/blob/64739c6185c64097cfac9e2fe23f22467fa979ff/background.js#L9

So looking into `modal.js` to see, what fills that value: https://github.com/Mte90/Share-Backported/blob/64739c6185c64097cfac9e2fe23f22467fa979ff/modal/modal.js#L37

Okay, so another argument. Found it gets invoked in https://github.com/Mte90/Share-Backported/blob/64739c6185c64097cfac9e2fe23f22467fa979ff/modal/modal.js#L274

That means, https://github.com/Mte90/Share-Backported/blob/64739c6185c64097cfac9e2fe23f22467fa979ff/modal/modal.js#L215-L256 is adjusting the shared URL. But where is the structure defined?

Turns out, in `modal.html`: https://github.com/Mte90/Share-Backported/blob/master/modal/modal.html#L12-L131

Means: It is not so easy with the current setup, since the share text is controlled by a Search-Parameter of the URL.

I could add a line that replaces the current „text” value (e.g. for Twitter), but it would need extensive testing to not break again after a new version of this web extension was published.
For private reasons I won't be able to do so myself before November.

Do you want me to proceed, @Mte90 ?

**Comment by Mte90** [comment]
I think that is good, you can open the PR with that code and I will work on the rest like testing and description in the settings page :-)

**Comment by Ryuno-Ki** [comment]
@Mte90 https://github.com/Mte90/Share-Backported/pull/124

**Comment by Mte90** [comment]
done :-)
